import Automata from './automata';
import Transicion from './transicion';
import Estado from './estado';
    var x:Automata = new Automata();
    var q0 = new Estado("q0",true,true);
    var q1 = new Estado("q1");
    var q2 = new Estado("q2");
    var q3 = new Estado("q3");
    q0.transiciones.set('1',new Transicion(q0,q1));
    q0.transiciones.set('0',new Transicion(q0,q2));
    q1.transiciones.set('1',new Transicion(q1,q0));
    q1.transiciones.set('0',new Transicion(q1,q3));
    q3.transiciones.set('0',new Transicion(q3,q1));
    q3.transiciones.set('1',new Transicion(q3,q2));
    q2.transiciones.set('0',new Transicion(q2,q0));
    q2.transiciones.set('1',new Transicion(q2,q3));
    x.estados.set(0,q0);
    x.estados.set(1,q1);
    x.estados.set(2,q2);
    x.estados.set(3,q3);
    console.log(x.evaluar("110000"));